compatibility_date = "2024-09-11"

name = "miners-online-web"
pages_build_output_dir = "./publish_out"

[[d1_databases]]
binding = "DB" # available in your Worker on env.DB
database_name = "minersonline-statistics"
database_id = "94afe8ac-b1bf-4d6b-be92-aa1e06ab86ec"