// @ts-nocheck -- skip type checking
import * as docs_3 from "../content/docs/core/rules.mdx?collection=docs"
import * as docs_2 from "../content/docs/core/index.mdx?collection=docs"
import * as docs_1 from "../content/docs/core/faq.mdx?collection=docs"
import * as docs_0 from "../content/docs/authentication/index.mdx?collection=docs"
import * as blogPosts_1 from "../content/blog/github-horror-story.md?collection=blogPosts"
import * as blogPosts_0 from "../content/blog/a-fresh-look-for-miners-online.md?collection=blogPosts"
import { _runtime } from "fumadocs-mdx/runtime/next"
import * as _source from "../source.config"
export const blogPosts = _runtime.doc<typeof _source.blogPosts>([{ info: {"path":"a-fresh-look-for-miners-online.md","fullPath":"content\\blog\\a-fresh-look-for-miners-online.md"}, data: blogPosts_0 }, { info: {"path":"github-horror-story.md","fullPath":"content\\blog\\github-horror-story.md"}, data: blogPosts_1 }]);
export const docs = _runtime.docs<typeof _source.docs>([{ info: {"path":"authentication/index.mdx","fullPath":"content\\docs\\authentication\\index.mdx"}, data: docs_0 }, { info: {"path":"core/faq.mdx","fullPath":"content\\docs\\core\\faq.mdx"}, data: docs_1 }, { info: {"path":"core/index.mdx","fullPath":"content\\docs\\core\\index.mdx"}, data: docs_2 }, { info: {"path":"core/rules.mdx","fullPath":"content\\docs\\core\\rules.mdx"}, data: docs_3 }], [{"info":{"path":"meta.json","fullPath":"content\\docs\\meta.json"},"data":{"pages":["core","authentication"]}}, {"info":{"path":"authentication/meta.json","fullPath":"content\\docs\\authentication\\meta.json"},"data":{"title":"Miners Online Authentication","pages":["---Introduction---","index","---API Definitions---","...(generated)"],"description":"Miners Online Authentication Documentation","root":true,"icon":"Key"}}, {"info":{"path":"core/meta.json","fullPath":"content\\docs\\core\\meta.json"},"data":{"title":"Core","pages":["---Introduction---","index","faq","rules"],"description":"Miners Online Core Documentation","root":true,"defaultOpen":true,"icon":"Gamepad2"}}])