# Generated by Django 4.2.9 on 2024-01-06 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['modified'], 'verbose_name': 'Page', 'verbose_name_plural': 'Pages'},
        ),
        migrations.RemoveField(
            model_name='page',
            name='created',
        ),
        migrations.RemoveField(
            model_name='page',
            name='updated',
        ),
        migrations.AlterField(
            model_name='page',
            name='modified',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
