import { BaseStyles, ThemeProvider } from '@primer/react'
import { StyledComponentsRegistry } from './registry'
import Navbar from '@/components/Navbar'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({children}: {children: React.ReactNode}) {
    return (
        // Note: the focus-visible polyfill adds additional attributes to `html`
        // that cause hydration mismatch errors
        <html lang="en" suppressHydrationWarning>
            <body>
                <StyledComponentsRegistry>
                    <ThemeProvider>
                        <BaseStyles>
                            <Navbar/>
                            {children}
                        </BaseStyles>
                    </ThemeProvider>
                </StyledComponentsRegistry>
            </body>
        </html>
    )
}